order = ["audio", "battery", "time"]
starting = "  ğŸ§  î‚³ "
separator = "  î‚³ "
#starting = "  ï…¼  î‚³ "
#separator = "  î‚³ "
ending = " "

[audio]
control = "Master"
mute = "MUTE"
template = "{ICO} {VOL}%"
#template = "S {VOL}%"
icons = ["ï©¾", "ï©¿", "ï©½"]

[backlight]
device = "intel_backlight"
#template = "L {BL}%"
template = "{ICO} {BL}%"
icons = ["ï—", "ï—", "ï—Ÿ"]

[battery]
charging = "ï‡¦ â–²"
discharging = "â–¼"
enable_notifier = false
notifier_critical = 10
notifier_levels = [2, 5, 10, 15, 20]
separator = " Â· "
no_battery = "ï"
icons = ["ï–", "ï•¹", "ï•º", "ï•»", "ï•¼", "ï•½", "ï•¾", "ï•¿", "ï–€", "ï–", "ï•¸"]

[cpu_load]
template = "{CL1} {CL5} {CL15}"
update_interval = 20

[network]
no_value = "NA"
template = "{IPv4} Â· {IPv6} Â· {ESSID}"

[time]
#format = "ï„³ ğŸ—“ï¸ %m/%d %I:%M"
format = "ğŸ—“ï¸ %m/%d %I:%M"
#format = "ğŸœ  ğŸ—“ï¸  âŒš %m/%d %H:%M"
update_seconds = false
